name: project_uas
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_launcher_icons: ^0.9.2
  hive: ^2.0.1
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  shared_preferences: ^2.2.2
  page_transition : ^2.0.9
  get :

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets : 
          - assets/image/
          - assets/json/
